# Optimización de Memoria para Taska OS (USB Live)

# Evitar el uso excesivo de intercambio (swap) en el almacenamiento USB
# swappiness=10 prioriza el uso de la memoria RAM y de ZRAM
vm.swappiness = 10

# Mejorar el caché del sistema de archivos en RAM
# 50 (menor que el valor por defecto de 100) hace que el sistema retenga metadatos
# de archivos en RAM por más tiempo, mejorando la velocidad de navegación de archivos.
vm.vfs_cache_pressure = 50

# Permitir un uso más eficiente de escrituras sucias en RAM
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10
