# Configuración de LightDM para Taska OS
# Configura el inicio de sesión automático y la sesión predeterminada

[LightDM]
run-directory=/run/lightdm

[Seat:*]
type=local
# El usuario por defecto creado por live-boot en Debian es 'user'
autologin-user=user
autologin-user-timeout=0
autologin-session=openbox
user-session=openbox
greeter-show-manual-login=false
greeter-hide-users=true
session-wrapper=/etc/X11/Xsession
